version: '3.8'

services:
    mongo:
        build: ./mongodb_replica
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_REPLICA_HOST: host.docker.internal
            MONGO_REPLICA_PORT: 27018
        ports:
            - '27018:27018'
    redis:
        image: 'bitnami/redis:latest'
        environment:
            - REDIS_PORT_NUMBER=6379
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379
    redis-commander:
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
        depends_on:
            - redis
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - mongo
